### PR TITLE
Made small cleanups for better consistency with Debian 8 which is wha…

### PR DESCRIPTION
**Pull request by bogdanr**
…t this is based on

### CODE REVIEW

**Comment by aboe76** [comment]
Hi @bogdanr, I think removing the comments isn't such a good idea, and the commented variables you changed are the defaults on openssh anyway, so can this be closed?

**Comment by ek9** [comment]
I would vote for closing this as I believe comments are useful, they are also usually in the default ssh configs provided by the distribution.

Although I agree we could update the header part (the `do not edit / manager by salt` part) and perhaps also hint to `man sshd_config` / `man ssh_config` too.

**Comment by 0xf10e** [comment]
I see no reason in removing useful comments just to make the file more look like the version Debian ships either.

**Comment by alxwr** [comment]
Sounds like YAGNI to me too. Sry.
It's a big effort to maintain one config layout for every distribution, which in the end we'll do, if someone needs this feature for another distribution.

SaltStack allows you to redefine any state file my placing it before the formula in `/srv/salt/master`'s `file_roots`. If someone really needs a certain layout, I think it's best to place it there. (Just my 2ct.)

I hate to say no (especially in an OpenSource context), but I'd vote for closing this PR too.

**Comment by puneetk** [comment]
You could conditionally source in a file just for debian, specify the source in the defaults and override using the debian os grain

**Comment by aboe76** [comment]
@bogdanr are you ok with the responses?

**Comment by bogdanr** [comment]
Yeah, I don't feel strongly about it anyways. Thanks for giving it a thought.

**Pull request closed without merging**
