### PR TITLE
Pillar openssh.known_hosts_salt_ssh

### PR DESCRIPTION
**Pull request by alxwr**
The goal of this PR is to emulate the functionality of SaltMine to gather SSH host keys.

There are now two additional ways to do this:

1. Re-use `salt-ssh`'s `known_hosts` file, which contains trusted keys.
2. Run a state file to provide a FS-based cache of host keys

(1 wins over 2 on a per-host basis)

@0xf10e @aboe76 What do you think?

From README.rst:

>To **include minions managed via `salt-ssh`** install the known_hosts_salt_ssh renderer:
>
>```
># in pillar.top:
>'*':
>  - openssh.known_hosts_salt_ssh
>
># In your salt/ directory:
># Link the pillar file:
>mkdir pillar/openssh
>ln -s ../../formulas/openssh-formula/_pillar/known_hosts_salt_ssh.sls >pillar/openssh/known_hosts_salt_ssh.sls
>Pillar openssh:known_hosts:salt_ssh overrides the Salt Mine.
>```
>
>The pillar is fed by a host key cache. Populate it by applying openssh.gather_host_keys to the salt >master:
>
>```
>salt 'salt-master.example.test' state.apply openssh.gather_host_keys
>```
>
>The state tries to fetch the SSH host keys via salt-ssh. It calls the command as user salt-master by default. The username can be changed via Pillar:
>
>```
>openssh:
>  known_hosts:
>    salt_ssh:
>      user: salt-master
>```
>
>You can use a cronjob to populate a host key cache:
>
>
>```
># crontab -e -u salt-master
>0 1 * * * salt 'salt-master.example.test' state.apply openssh.gather_host_keys
>```
>
>Or just add it to your salt master:
>
>```
># states/top.sls:
>base:
>  salt:
>    - openssh.known_hosts_salt_ssh
>```
>
>You can also use a "golden" known hosts file. It overrides the keys fetched by the cronjob. This lets you >re-use the trust estabished in the salt-ssh user's known_hosts file:
>
>```
># In your salt/ directory: (Pillar expects the file here.)
>ln -s /home/salt-master/.ssh/known_hosts ./known_hosts
>```
>
>```
># Test it:
>salt-ssh 'minion' pillar.get 'openssh:known_hosts:salt_ssh'
>```

### CODE REVIEW

**Comment by alxwr** [comment]
I just found a obsolete file in the PR 10 seconds after opening it. Please squash my commits to hide my blunder. :-)

**Comment by 0xf10e** [comment]
Nice.addition :+1:

Do jinja macros have defaults for kwargs
so we can have a `include_localhost=False`
in its definition?

**Comment by alxwr** [comment]
@0xf10e This has already been implemented: https://github.com/saltstack-formulas/openssh-formula/pull/128/files#diff-e78a53ca47e56137f859f577db93cfe8R61

**Comment by aboe76** [comment]
@0xf10e are you OK with squash + merging?

**Comment by alxwr** [comment]
Ping! :-)

**Comment by aboe76** [comment]
@alxwr merged it.

**Comment by 0xf10e** [comment]
@aboe76 oh, crap, sorry, missed the request for review ^^""

**Pull request merged**
