### PR TITLE
Opt-in to enforce RSA key length

### PR DESCRIPTION
**Pull request by alxwr**
I'll merge in two to three days if there are no concerns with my addition.

Alex

### CODE REVIEW

**Comment by babilen** [comment]
What does this do exactly?

**Comment by alxwr** [comment]
>What does this do exactly?

If the key length is lower than the configured value, the key is deleted and an new one (with the correct key length) is generated.

**Comment by babilen** [comment]
Thanks - I asked, because this PR doesn't really contain much information as to why one would merge it. It's also preferred to have other people merge your changes, but I wouldn't have been comfortable doing so as I had to, more or less, figure out what is going on myself.

Thanks for the contribution!

**Comment by alxwr** [comment]
Thanks, I'll keep both (add more info; let others merge) in mind! :-)

**Pull request merged**
