### PR TITLE
CentOS does not support ed25519; fixes #98

### LINKED ISSUE #98: CentOS 6: check_cmd broken/unsupported key type ed25519
While testing #97 I've noticed the `check_cmd` fails on CentOS 6:
```
[root@centos6minion ~]# tail -n 5 /var/log/salt/minion                                                                                                                                         
2017-06-22 02:30:33,752 [salt.state       ][INFO    ][4647] File /etc/ssh/ssh_config is in the correct state
2017-06-22 02:30:33,753 [salt.state       ][INFO    ][4647] Completed state [/etc/ssh/ssh_config] at time 02:30:33.752483
2017-06-22 02:40:47,330 [salt.loaded.int.module.cmdmod              ][ERROR   ][5092] Command '/usr/sbin/sshd -t -f /tmp/tmptj9aZz' failed with return code: 1
2017-06-22 02:40:47,331 [salt.loaded.int.module.cmdmod              ][ERROR   ][5092] output: /tmp/tmptj9aZz: Permission denied
2017-06-22 02:40:47,332 [salt.state                                 ][ERROR   ][5092] check_cmd execution failed
[root@centos6minion ~]# ls -l /tmp/tmpP4oYT8
-rw-r--r--. 1 root root 4479 Jun 22 02:49 /tmp/tmpP4oYT8
```
The "Permission denied" error is pretty strange, could even be a bug in CentOS 6's python (see versions-report below). But I have another concern: When I run the check manually there's the problem with missing hostkeys
```
[root@centos6minion ~]# sshd -t -f /tmp/tmpP4oYT8
Could not load host key: /etc/ssh/ssh_host_ecdsa_key
Could not load host key: /etc/ssh/ssh_host_ed25519_key
```
While one can manually generate an ECDSA hostkey, ED25519 keys are not supported on CentOS 6:
```
[root@centos6minion ~]# ssh-keygen -t ed25519
unknown key type ed25519
```
Removing `'ed25519'` from `openssh/config.sls` doesn't help as the `check_cmd` still fails with this "Permission denied" error. Though the SSH-server actually starts when a host key listed in its config is missing (tested by removing the `check_cmd` line from `openssh/config.sls`).

PS: Versions-report and pillar data:
```
[root@centos6minion ~]# salt-call --versions-report                                            
           Salt: 2015.5.10                                                                     
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)                                     
         Jinja2: 2.2.1                         
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed
[root@centos6minion ~]# salt-call pillar.items
local:
    ----------
    __formulas:
        ----------
        print_template_url:
            True
    openssh-formula:
        ----------
        print_template_url:
            None
    salt:
        ----------
        minion:
            ----------
            master:
                192.168.178.64
    ssh_config:
        ----------
        SendEnv:
            LANG LC_* EDITOR EMAIL GIT_AUTHOR_EMAIL GIT_AUTHOR_NAME VISUAL
    sshd_config:
        ----------
        AcceptEnv:
            LANG LC_* EDITOR EMAIL GIT_AUTHOR_EMAIL GIT_AUTHOR_NAME VISUAL
        PrintMotd:
            yes
```

### PR DESCRIPTION
**Pull request by alxwr**
* split map.jinja according to template-formula
* Made host key algos configurable; dropped DSA
* CentOS does not support ed25519; fixes #98

After refactoring `map.jinja` it should now be easy to exclude certain host key algorithms for older systems.

If this PR is accepted and merged, I plan on implementing an opt-out (`use_check_cmd: False`) to solve #147.

Tested on Ubuntu 18.04 and FreeBSD 11.2, but I don't have a CentOS 6 here. (Should work though.)

@hudecof @kadogo Could you please test this PR?

### CODE REVIEW

**Comment by hudecof** [comment]
@alxwr unfortunate I gave up saltstack and returned to ansible, so my dev environment do not exists any more ;(

**Comment by myii** [comment]
Have performed some basic testing **limited to the YAML files and `map.jinja` refactoring**.  Tested on an Ubuntu minion with `pillar.example`.  Comparing before and after this PR gives:

```diff
--- master
+++ alxwr:issue-98
@@ -72,6 +72,7 @@
   "generate_ed25519_keys": false,
   "generate_rsa_keys": false,
   "generate_rsa_size": 4096,
+  "host_key_algos": "ecdsa,ed25519,rsa",
   "known_hosts": {
     "aliases": [
       "cname-to-minion.example.org",
@@ -129,6 +130,55 @@
   "sshd_config_src": "salt://openssh/files/sshd_config",
   "sshd_config_user": "root",
   "sshd_enable": true
 }
+{
+  "Hosts": {
+    "*": {
+      "AddressFamily": "any",
+      "BatchMode": "yes",
+      "CheckHostIP": "yes",
+      "Cipher": "3des",
+      "Ciphers": [
+        "chacha20-poly1305@openssh.com",
+        "aes256-gcm@openssh.com",
+        "aes128-gcm@openssh.com",
+        "aes256-ctr",
+        "aes192-ctr",
+        "aes128-ctr"
+      ],
+      "ConnectTimeout": 0,
+      "ForwardAgent": false,
+      "ForwardX11": false,
+      "GSSAPIAuthentication": false,
+      "GSSAPIDelegateCredentials": false,
+      "HostbasedAuthentication": false,
+      "IdentityFile": "~/.ssh/id_rsa",
+      "KexAlgorithms": [
+        "curve25519-sha256@libssh.org",
+        "diffie-hellman-group-exchange-sha256",
+        "diffie-hellman-group-exchange-sha1",
+        "diffie-hellman-group14-sha1"
+      ],
+      "MACs": [
+        "hmac-sha2-512-etm@openssh.com",
+        "hmac-sha2-256-etm@openssh.com",
+        "umac-128-etm@openssh.com",
+        "hmac-sha2-512",
+        "hmac-sha2-256",
+        "umac-128@openssh.com"
+      ],
+      "PasswordAuthentication": true,
+      "PermitLocalCommand": "no",
+      "Port": 22,
+      "Protocol": 2,
+      "RSAAuthentication": true,
+      "RhostsRSAAuthentication": false,
+      "StrictHostKeyChecking": false,
+      "Tunnel": "no",
+      "TunnelDevice": "any:any",
+      "VisualHostKey": "no"
+    }
+  }
+}
 {
   "AcceptEnv": "LANG LC_*",
```

Looking at the additions, these are both expected due to:

1. [`host_key_algos` added to `defaults.yaml`](https://github.com/saltstack-formulas/openssh-formula/pull/151/files#diff-bbffb06809bf2d748c708b3e15ca1856R23).
1. [`ssh_config` also being exported from `map.jinja`](https://github.com/saltstack-formulas/openssh-formula/pull/151/files#diff-e2de1c947bd07ac512ee47da00abad1dR28).

So no regressions detected for this part of the refactoring, according to this limited testing at least.

Good work, @alxwr!

**Comment by alxwr** [comment]
I may have found a bug when using `salt-ssh`. `defaults.merge` does not seem to work.

**Comment by myii** [comment]
@alxwr @aboe76 @LloydArmstrong It looks like https://github.com/saltstack-formulas/redis-formula/issues/75 really is a problem again re: `salt-ssh` vs. `defaults.merge`.  Is this a bug upstream?

**Comment by alxwr** [comment]
@aboe76 @myii @javierbertoli This PR now works with both `salt` and `salt-ssh`.

**Comment by myii** [comment]
@alxwr Would you be able to confirm that `defaults.merge` is not available, like in this comment here:

* https://github.com/saltstack-formulas/redis-formula/issues/75#issuecomment-459667105

**Comment by alxwr** [comment]
> @alxwr Would you be able to confirm that `defaults.merge` is not available, like in this comment here:
> 
> * [saltstack-formulas/redis-formula#75 (comment)](https://github.com/saltstack-formulas/redis-formula/issues/75#issuecomment-459667105)

Yes. I got the same message in my debug log:

```
[DEBUG   ] Could not LazyLoad defaults.merge: 'defaults.merge' is not available.
```

**Comment by myii** [comment]
@alxwr Upstream bug report: https://github.com/saltstack/salt/issues/51605.

**Comment by alxwr** [comment]
@myii Thanks!

**Comment by alxwr** [comment]
@myii I'm running `salt-ssh` from a FreeBSD machine against a Debians minion.

```
% salt --versions-report
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.2.5
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15 (default, Dec 27 2018, 00:23:42)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3
 
System Versions:
           dist:   
         locale: UTF-8
        machine: amd64
        release: 11.2-RELEASE-p8
         system: FreeBSD
        version: Not Installed
```

**Comment by myii** [comment]
@alxwr Thanks, I've updated the upstream report.

I've also run the same test again for `map.jinja` and everything is still merging the with the same expected diff [as above](https://github.com/saltstack-formulas/openssh-formula/pull/151#issuecomment-462798913).

**Comment by aboe76** [comment]
@javierbertoli ping

**Comment by aboe76** [comment]
@alxwr I like this map.jinja style it looks like a merger between new and old style...

**Comment by alxwr** [comment]
> @alxwr I like this map.jinja style it looks like a merger between new and old style...

Well, it actually is. :smile: Trying to take the best of both worlds.

**Comment by myii** [comment]
Merged.  Thanks for the PR, @alxwr.  And to @aboe76 and @javierbertoli for the reviews.

**Pull request merged**
