### PR TITLE
fix(test): make rubocop happy

### PR DESCRIPTION
**Pull request by baby-gnu**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [x] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Related issues and/or pull requests

#167

### Describe the changes you're proposing

This PR:

- remove the Serverspec files because everything is covered by Inspec
- make rubocop happy with the tests code

### Debug log showing how the proposed changes work

```
$ rubocop -d
For /home/travis/build/baby-gnu/openssh-formula: configuration from /home/travis/build/baby-gnu/openssh-formula/.rubocop.yml
Default configuration from /home/travis/.rvm/gems/ruby-2.6.5/gems/rubocop-0.88.0/config/default.yml
The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file:
 - Layout/EmptyLinesAroundAttributeAccessor (0.83)
 - Layout/SpaceAroundMethodCallOperator (0.82)
 - Lint/DeprecatedOpenSSLConstant (0.84)
 - Lint/DuplicateElsifCondition (0.88)
 - Lint/MixedRegexpCaptureTypes (0.85)
 - Lint/RaiseException (0.81)
 - Lint/StructNewOverride (0.81)
 - Style/AccessorGrouping (0.87)
 - Style/ArrayCoercion (0.88)
 - Style/BisectedAttrAccessor (0.87)
 - Style/CaseLikeIf (0.88)
 - Style/ExponentialNotation (0.82)
 - Style/HashAsLastArrayItem (0.88)
 - Style/HashEachMethods (0.80)
 - Style/HashLikeCase (0.88)
 - Style/HashTransformKeys (0.80)
 - Style/HashTransformValues (0.80)
 - Style/RedundantAssignment (0.87)
 - Style/RedundantFetchBlock (0.86)
 - Style/RedundantFileExtensionInRequire (0.88)
 - Style/RedundantRegexpCharacterClass (0.85)
 - Style/RedundantRegexpEscape (0.85)
 - Style/SlicingWithRange (0.83)
For more information: https://docs.rubocop.org/rubocop/versioning.html
Inspecting 5 files
Scanning /home/travis/build/baby-gnu/openssh-formula/Gemfile
.Scanning /home/travis/build/baby-gnu/openssh-formula/bin/kitchen
.Scanning /home/travis/build/baby-gnu/openssh-formula/test/integration/default/controls/config_spec.rb
.Scanning /home/travis/build/baby-gnu/openssh-formula/test/integration/default/controls/packages_spec.rb
.Scanning /home/travis/build/baby-gnu/openssh-formula/test/integration/default/controls/services_spec.rb
.

5 files inspected, no offenses detected
Finished in 0.2538999359999963 seconds
The command "rubocop -d" exited with 0.
```

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by myii** [comment]
@baby-gnu Thanks for the PR.  Couple of bits of feedback for you:

---

#### `feat(test): remove serverspec files`

There were a few discussions about this when InSpec tests were added here:

* https://github.com/saltstack-formulas/openssh-formula/issues/165#issuecomment-519187608 -- starts at the end of the comment above this one.
* https://github.com/saltstack-formulas/openssh-formula/pull/166#issue-316541412 -- "didn't convert, just added the InSpec tests".
* https://github.com/saltstack-formulas/openssh-formula/issues/167

I didn't want to be presumptuous at the time and simply remove the Serverspec tests.  I think we're OK now so should be able to remove but not 100% sure about where we stand with #167.

---

#### `fix(inspec): make rubocop happy`

Since Rubocop is now working, we can merge it into the main lint job:

https://github.com/saltstack-formulas/openssh-formula/blob/d0d2864d13a1eb09bd6231711eb82c5d260a6a12/.travis.yml#L57-L58

So that's simply using the structure from the `template-formula` here.

**Comment by baby-gnu** [comment]
#### `feat(test): remove serverspec files`

I wasn't sure about this but found some [discussion](https://github.com/saltstack-formulas/openssh-formula/issues/165#issuecomment-529690762) about [doing like in vault](https://github.com/saltstack-formulas/vault-formula/pull/32).

So I thought that getting rid of the files would have been a first step.

#### `fix(inspec): make rubocop happy`

Yes, I plan to do that separately with the update of the matrix and all.

**Comment by myii** [comment]
@baby-gnu OK, let's get this merged!

**Comment by myii** [comment]
Closed #167, since no longer seems valid.

**Pull request merged**
