### PR TITLE
Fix the default Subystem sftp-server path for SLE

### PR DESCRIPTION
**Pull request by tampakrap**

### CODE REVIEW

**Comment by aboe76** [comment]
thanks @tampakrap

**Comment by tampakrap** [comment]
Unfortunately it is not sufficient or wrong, it does nothing

**Comment by adamcharvey** [comment]
My guess is that the files/sshd_config is not pulling values from the map.jinja.  I tried to do the same w/centos and ubuntu.  More than likely need to import the values from map.jinja or refactor.  Ugh

**Comment by aboe76** [comment]
@tampakrap ,

Can you try with this in your sshd_config file:

```
{%- from "openssh/map.jinja" import openssh with context -%}
{%- set sshd_config = pillar.get('sshd_config',('openssh:sshd_config')) -%}
{#- present in sshd_config and known in actual file options -#}
{%- set processed_options = [] -%}
```

**Pull request merged**
