### PR TITLE
Add AuthorizedKeysCommand support

### PR DESCRIPTION
**Pull request by kyrias**

### CODE REVIEW

**Comment by gravyboat** [comment]
Would you mind adding this to the pillar? Once that's done we can get it merged.

**Comment by kyrias** [comment]
Ah, I didn't since `AuthorizedKeysFile` wasn't in there, and I'm not sure what to set it to in the pillar, since there's not really a standard command, but sure.

**Comment by gravyboat** [comment]
Thanks!

**Comment by kyrias** [comment]
Do you want me to file a PR with a full example pillar?

**Comment by gravyboat** [comment]
@kyrias If you want to update the example pillar with more options feel free to do so! If not, I understand, we're all busy and it's not your fault it was overlooked in the past.

**Comment by kyrias** [comment]
@gravyboat The readme says that the example pillar will generate the default `sshd_config` on Debian Wheezy, but I don't have access to any Debian systems to fill it out according to that.  So should I leave it as-is, or just fill it out with the default values from upstream OpenSSH where possible?

**Comment by gravyboat** [comment]
Just leave it as is I would say, better safe than sorry.

**Pull request merged**
