### PR TITLE
Add variables for file owner and mode

### PR DESCRIPTION
**Pull request by amendlik**
Permit customization of file owner and mode for `ssh_config` and `sshd_config`. I added this because the current default is 644, but CIS benchmarks recommend 600.

### CODE REVIEW

**Comment by 0xf10e** [comment]
As long as `ssh_config_mode: '600'` doesn't end up in the defaults or `pillar.example` it's fine with me. This would prevent any global configuration of a host's OpenSSH client - and is a rather strange idea in my opinion.

**Comment by amendlik** [comment]
This PR does not change the current behavior in any way. It just makes it possible for the user to configure some hard coded values.

@0xf10e is right about `ssh_config_mode: '600'`. The CIS benchmark only specifies the permissions for `sshd_config`

**Comment by aboe76** [comment]
@amendlik can you then please revert the permissions on ssh_config, to be like the defaults in the kitchen.yml, somebody could think that's a good idea and see it as acceptable.

**Comment by 0xf10e** [comment]
Looks good to me

**Comment by aboe76** [comment]
@amendlik could you please rebase, then I will merge it.

**Comment by aboe76** [comment]
Thanks, merging now.

**Comment by alxwr** [comment]
66c954e sets correct default values for OpenBSD and FreeBSD and repaces `root_group`.

**Pull request merged**
