### PR TITLE
add more authentication options

### PR DESCRIPTION
**Pull request by aboe76**
Needed these two authentication options to be set.
- MaxAuthTries
- MaxSessions

### CODE REVIEW

**Comment by gravyboat** [comment]
Are those values you have the defaults for openssh?

**Comment by babilen** [comment]
They are, yeah

**Comment by aboe76** [comment]
@gravyboat, Sorry next time I will mention that I have added the save defaults... ;)
```man sshd_config```

**Comment by gravyboat** [comment]
@aboe76 No worries, I just like to double check since I merged one a while back that was incorrect.

**Pull request merged**
