### PR TITLE
drop default values (fixes #102)

### LINKED ISSUE #102: Deprecated sshd options
I am using this formula to manage openssh in small home environment, and while applying some states I came across deprecation warnings in the sshd logs of a Fedora 26 minion:

```
$ journalctl -u sshd
Jul 22 12:51:24  systemd[1]: Starting OpenSSH server daemon...
Jul 22 12:51:24  sshd[12040]: /etc/ssh/sshd_config line 23: Deprecated option UsePrivilegeSeparation
Jul 22 12:51:24  sshd[12040]: /etc/ssh/sshd_config line 26: Deprecated option KeyRegenerationInterval
Jul 22 12:51:24  sshd[12040]: /etc/ssh/sshd_config line 27: Deprecated option ServerKeyBits
Jul 22 12:51:24  sshd[12040]: /etc/ssh/sshd_config line 45: Deprecated option RSAAuthentication
Jul 22 12:51:24  sshd[12040]: /etc/ssh/sshd_config line 54: Deprecated option RhostsRSAAuthentication
Jul 22 12:51:24  sshd[12040]: Could not load host key: /etc/ssh/ssh_host_dsa_key
Jul 22 12:51:24  sshd[12040]: Server listening on 0.0.0.0 port 22.
Jul 22 12:51:24  sshd[12040]: Server listening on :: port 22.
Jul 22 12:51:24  systemd[1]: Started OpenSSH server daemon.
```
(I don't have the deprecated options specified in Pillar.)

I did a little research and it seems to be that these options were removed from the sshd_config file in recent versions of OpenSSH 7, in preparation of removing support for SSH protocol 1. This makes sense as Fedora 26 uses version 7.5 of OpenSSH and I don't get these warnings when running the state on Centos 7.3 systems which are using version 6.6 of OpenSSH.

This isn't a major issue as nothing is broken of course, but I thought it might be a good idea to bring it up.

### PR DESCRIPTION
**Pull request by alxwr**
fixes #102 

tested on:

- FreeBSD 10.3
- Debian 8.9
- Ubuntu 14.04

### CODE REVIEW

**Comment by aboe76** [comment]
@alxwr I want to test this first before I merge.

**Comment by aboe76** [comment]
@alxwr looks good except that it leaves a lot of empty lines and comments between the options...
which makes a weird sshd_config file.

**Comment by alxwr** [comment]
@aboe76 I'll try to optimize that. :-)

**Comment by alxwr** [comment]
@aboe76 I removed the redundant white space.

**Comment by aboe76** [comment]
@alxwr somewhere around AllowUsers, and allowgroups it merges all the lines together.
```
AllowUsers xxxx xxxxAllowGroups xxxxKexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctrMACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-sha1,umac-128@openssh.comCompression no
```

It should be:
```
AllowUsers XXXX XXXXX
AllowGroups XXXXX
KexAlgorithms curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,hmac-sha1,umac-128@openssh.com
Compression no
```

**Comment by alxwr** [comment]
@aboe76 whitespace issues should be fixed. :-)
Please test again!

**Comment by aboe76** [comment]
@alxwr thanks looks good.

**Comment by aboe76** [comment]
@whiteinge can you give some feedback?

**Comment by aboe76** [comment]
@alxwr still see some trouble with ciphers being on the same line as kexalgorithms.

**Comment by alxwr** [comment]
@aboe76 Reproduced and fixed the bug. :-) Thanks for testing!

Maybe squash the fix-of-the-fix commits before merging to increase clarity?

**Comment by aboe76** [comment]
@alxwr thanks for this.

**Pull request merged**
