### PR TITLE
Fix invalid require_in sshd_config for key states

### PR DESCRIPTION
**Pull request by tmeneau**
The purpose of this pull request is to allow using the config.sls state exclusively to configure keys (RSA, DSA, etc...) without managing the `sshd_config` (see issue #130). 

This is a pretty simple change that adds conditional evaluation to the `require_ins` applied to the key management states to make the key management states a requisite of the `sshd_config` management state.

@aboe76 @alxwr -- are either of you free to review this?

### CODE REVIEW

**Comment by javierbertoli** [comment]
@tmeneau you seem to have missed an `if` block around [these lines](https://github.com/tmeneau/openssh-formula/blob/63ad14efb1fa6d7c2aab7aa295941acd504c329f/openssh/config.sls#L116-L117)?

Other than that, it LGTM?

**Comment by tmeneau** [comment]
Thanks for the review @javierbertoli! 

I actually didn't bother to add a conditional to those lines since `sshd_config` (which is used to [compute the new manage_sshd_config variable](https://github.com/tmeneau/openssh-formula/blob/63ad14efb1fa6d7c2aab7aa295941acd504c329f/openssh/config.sls#L3)) [must be defined for that last state to exist at all](https://github.com/tmeneau/openssh-formula/blob/63ad14efb1fa6d7c2aab7aa295941acd504c329f/openssh/config.sls#L111).

Would you be willing to merge this in?

**Comment by tmeneau** [comment]
Thanks @javierbertoli!

**Comment by javierbertoli** [comment]
Thanks to you :smile:

**Pull request merged**
